### ISSUE TITLE
Similar project

### ISSUE THREAD

**Issue by angelozerr** [aleksandr-m/strutsclipse#1]
@aleksandr-m we have similar project. [Eclipse WTP/XML Search](https://github.com/angelozerr/eclipse-wtp-xml-search) provides a XML Search engine that you can use inside WTP XML to manage (easily) completion, hover, hyperlink, validation and Ctrl+Shift+G (to retrieve referenced nodes) for your custom XML, HTML, JSP files.

It exists an implementation for Struts2 https://github.com/angelozerr/eclipse-wtp-xml-search/wiki/Struts2-IDE

Note that [Eclipse WTP/XML Search](https://github.com/angelozerr/eclipse-wtp-xml-search) is now used by Liferay IDE which contributes it and I hope this project will belong to one day to WTP.

I have no time to support Struts2 IDE, but if you like it and you wish to integrate it in your project, I will be happy to help you. Hope we will work together.

**Comment by aleksandr-m** [comment]
Hi Angelo,
I see a couple of interesting points which your plugin might help to solve, especially finding information about interceptor stacks.

Do you have any dev documentation about your plugin?

Thank you for informing me about it. ;)

**Comment by angelozerr** [comment]
> I see a couple of interesting points which your plugin might help to solve, especially finding information about interceptor stacks.

Cool! I think Ctrl+Shift+G can be helpful too.

> Do you have any dev documentation about your plugin?

No -( I had starte dto write articles at https://angelozerr.wordpress.com/about/eclipse-wtp-xml-search/ but no time to continue.

The basic idea is to declare in your plugin.xml the references with XPath (XML node -> XML node, XML node -> Java Class, etc) and after you benefit with completion, hyperlink, hover and Ctrl+Shift+G.

For instance for interceptor-ref https://github.com/angelozerr/eclipse-wtp-xml-search/blob/master/struts2/org.apache.struts2.ide.core/plugin.xml#L93 : 

``` xml
<reference>
    <from path="/struts//interceptor-ref"
          targetNodes="@name"
          querySpecificationId="struts2.querySpecification" />
    <to path="/struts//interceptor"
        targetNodes="@name"
        querySpecificationId="struts2.querySpecification"
        additionalProposalInfoProviderId="struts2.interceptor.info" />
    <to path="/struts//interceptor-stack"
        targetNodes="@name"
        querySpecificationId="struts2.querySpecification"
        additionalProposalInfoProviderId="struts2.interceptor-statck.info" />                   
</reference>
```

If you need more info, please create issues and I will try to write something in the wiki, but I'm very busy with other projects-(
